services:
  - type: web
    name: puppeteer-app
    env: node
    buildCommand: |
      apt-get update && apt-get install -y chromium-browser
      which chromium-browser
      chromium-browser --version
    startCommand: node index.js
    runtime: node 18
