services:
  - type: web
    name: puppeteer-app
    env: node
    buildCommand: npm install
    startCommand: node index.js
    runtime: node 18
    install:
      - apt-get update
      - apt-get install -y chromium-browser
