services:
  - type: web
    name: puppeteer-app
    env: node
    buildCommand: |
      apt-get update
  apt-get install -y wget
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  apt-get install -y ./google-chrome-stable_current_amd64.deb
  which google-chrome-stable
  google-chrome-stable --version
    startCommand: node index.js
    runtime: node 18
  
